import { ApiError } from '../../../common/errors/http-error.js';
import { getLlmClient } from '../../llm/llm-provider.js';
import { type LlmChatResponse, type LlmMessage, type LlmTokenUsage } from '../../llm/llm.types.js';
import { resolveModelForAgent, type AgentType } from '../../llm/model-registry.js';
import { type RagSearchResult } from '../../rag/rag.types.js';
import { type RagCitation } from '../../rag/rag.types.js';
import { findActivePromptTemplate } from '../prompts/prompt.repository.js';
import {
  createPolicyQaSourceId,
  fallbackService,
  normalizeQuestion,
} from '../../fallback/fallback.service.js';
import {
  attachFallbackTaskToRun,
  updateRunState,
  updateRunStateIfLeased,
} from '../agents.repository.js';
import { type AgentGraphState, type AgentRunRow } from '../agents.types.js';
import {
  type AgentOutputSchema,
  validateAgentOutput,
} from './agent-output-schema.js';
import { saveCheckpoint } from './checkpoint.repository.js';
import { agentStepRecorder } from './step-recorder.js';
import { wrapUntrustedContent } from './agent-security.js';
import { agentToolRunner } from '../tools/tool-runner.js';
import { runAgentToolLoop } from './agent-tool-loop.js';
import { agentRuntimeLoop } from './agent-runtime-loop.js';

const PROMPT_VERSION = 'batch18.v1';

type SupervisorOutput = {
  intent_type: string;
  confidence: number;
  missing_fields?: string[];
  next_node?: string;
};

type RetrievalPlannerOutput = {
  query: string;
  policy_id?: string | null;
  limit?: number;
};

type PolicyAnalysisOutput = {
  result: string;
  explanation: string;
  confidence: number;
  missing_fields?: string[];
  matched_conditions?: unknown[];
  answer?: string;
};

type RiskJudgeOutput = {
  approved: boolean;
  should_fallback: boolean;
  reasons?: string[];
  confidence: number;
};

type AgentJsonResponse<TJson> = LlmChatResponse<TJson> & {
  tool_results?: Array<{
    tool_name: string;
    output: unknown;
  }>;
};

export class ConsultationGraphRunner {
  async run(input: {
    run: AgentRunRow;
    actor_id: string;
    trace_id: string;
  }): Promise<AgentRunRow> {
    return agentRuntimeLoop.runConsultation(input);
  }

  private async runGraphSequence(input: {
    run: AgentRunRow;
    actor_id: string;
    trace_id: string;
  }): Promise<AgentRunRow> {
    const question = readQuestion(input.run.state);
    let state = await this.runSupervisor(input.run, question);
    state = await this.runRetrievalPlanner(input, state, question);
    if (state.retrieval?.backend_mode === 'pending') {
      state = await this.runRagTool(input, state);
    }

    if ((state.retrieval?.citations.length ?? 0) === 0) {
      return this.interruptForFallback(input, state, 'policy_qa_no_citation');
    }

    state = await this.runPolicyAnalysis(input.run, state, question);
    state = await this.runRiskJudge(input.run, state);

    if (state.judge?.should_fallback || !state.judge?.approved) {
      return this.interruptForFallback(input, state, 'policy_qa_risk_judge_fallback');
    }

    const citations = state.retrieval?.citations ?? [];
    const answer = buildFinalAnswer({
      analysis: state.policy_analysis?.answer
        ?? state.policy_analysis?.result
        ?? state.policy_analysis?.explanation
        ?? 'Policy answer generated by agent runtime.',
      citations,
    });
    state = {
      ...state,
      current_node: 'final',
      final: {
        status: 'answered',
        answer,
        citations,
        next_actions: [],
      },
    };
    await agentStepRecorder.recordStep({
      run_id: input.run.run_id,
      node_name: 'final',
      agent_type: 'final',
      status: 'completed',
      input: {
        citation_count: citations.length,
      },
      output: state.final,
    });
    await saveCheckpoint({
      run_id: input.run.run_id,
      state,
      status: 'completed',
    });

    return this.updateRun(input.run.run_id, 'completed', 'final', state);
  }

  async resume(input: {
    run: AgentRunRow;
    actor_id: string;
    trace_id: string;
    task_id: string;
    resume_payload: Record<string, unknown>;
  }): Promise<AgentRunRow> {
    const manualCitation = input.resume_payload.manual_citation;
    const manualAnswer = input.resume_payload.answer;
    let state: AgentGraphState = {
      ...input.run.state,
      current_node: 'human_fallback_resume',
      fallback: {
        ...(input.run.state.fallback ?? {}),
        task_id: input.task_id,
        reason: input.run.state.fallback?.reason ?? 'policy_qa_resumed',
        resume_payload: input.resume_payload,
      },
    };

    if (manualCitation && typeof manualCitation === 'object') {
      state = {
        ...state,
        retrieval: {
          query: state.retrieval?.query ?? readQuestion(state),
          citations: [manualCitation],
          confidence: 1,
          backend_mode: 'manual_resume',
        },
      };
    }
    if (typeof manualAnswer === 'string' && manualAnswer.trim() !== '') {
      state = {
        ...state,
        policy_analysis: {
          result: 'manual_resume_answer',
          matched_conditions: [],
          missing_fields: [],
          explanation: manualAnswer.trim(),
          confidence: 1,
          answer: manualAnswer.trim(),
        },
      };
    }

    await agentStepRecorder.recordStep({
      run_id: input.run.run_id,
      node_name: 'human_fallback_resume',
      agent_type: 'human_fallback',
      status: 'completed',
      input: {
        task_id: input.task_id,
      },
      output: {
        resumed: true,
        manual_citation_supplied: Boolean(manualCitation),
        manual_answer_supplied: typeof manualAnswer === 'string',
      },
    });
    await saveCheckpoint({ run_id: input.run.run_id, state });

    if ((state.retrieval?.citations.length ?? 0) === 0) {
      state = {
        ...state,
        current_node: 'final',
        final: {
          status: 'manual_review',
          answer:
            'Policy consultation was resumed, but no usable citation was supplied.',
          citations: [],
          next_actions: ['manual_fallback'],
        },
      };
    } else {
      state = await this.runRiskJudge(input.run, state);
      const citations = state.retrieval?.citations ?? [];
      state = {
        ...state,
        current_node: 'final',
        final: {
          status: state.judge?.should_fallback ? 'manual_review' : 'answered',
          answer: buildFinalAnswer({
            analysis: state.policy_analysis?.answer
              ?? state.policy_analysis?.explanation
              ?? 'Policy answer resumed by agent runtime.',
            citations,
          }),
          citations,
          next_actions: state.judge?.should_fallback ? ['manual_fallback'] : [],
        },
      };
    }

    await agentStepRecorder.recordStep({
      run_id: input.run.run_id,
      node_name: 'final',
      agent_type: 'final',
      status: 'completed',
      input: {
        resumed_from_task_id: input.task_id,
      },
      output: state.final,
    });
    await saveCheckpoint({
      run_id: input.run.run_id,
      state,
      status: 'completed',
    });
    return this.updateRun(input.run.run_id, 'completed', 'final', state);
  }

  private async runSupervisor(
    run: AgentRunRow,
    question: string,
  ): Promise<AgentGraphState> {
    const output = await this.callJsonAgent<SupervisorOutput>({
      run,
      node_name: 'supervisor',
      agent_type: 'supervisor',
      schema: 'supervisor',
      input: { question },
      system_prompt: [
        'You are the supervisor for a policy consultation workflow.',
        'Return JSON with intent_type, confidence, missing_fields, next_node.',
      ].join(' '),
      user_prompt: wrapUntrustedContent('user_question', question),
    });
    const state: AgentGraphState = {
      ...run.state,
      current_node: 'supervisor',
      intent: {
        intent_type: output.json?.intent_type ?? 'policy_qa',
        confidence: toConfidence(output.json?.confidence),
        missing_fields: output.json?.missing_fields ?? [],
        next_node: output.json?.next_node ?? 'retrieval_planner',
      },
    };
    await saveCheckpoint({ run_id: run.run_id, state });
    return state;
  }

  private async runRetrievalPlanner(
    input: {
      run: AgentRunRow;
      actor_id: string;
      trace_id: string;
    },
    state: AgentGraphState,
    question: string,
  ): Promise<AgentGraphState> {
    const run = input.run;
    const output = await this.callJsonAgent<RetrievalPlannerOutput>({
      run: { ...run, state },
      node_name: 'retrieval_planner',
      agent_type: 'retrieval_planner',
      schema: 'retrieval_planner',
      input: { question, policy_id: state.input.policy_id ?? null },
      system_prompt: [
        'You plan policy retrieval.',
        'You may call rag.search once when citations are needed.',
        'After tool results are returned, produce final JSON with query, optional policy_id, and limit.',
      ].join(' '),
      user_prompt: wrapUntrustedContent('user_question', question),
      tools: {
        allowed_tools: ['rag.search'],
        scope: {
          policy_id: typeof state.input.policy_id === 'string'
            ? state.input.policy_id
            : undefined,
        },
        context: {
          run_id: input.run.run_id,
          actor_id: input.actor_id,
          trace_id: input.trace_id,
          agent_type: 'retrieval_planner',
          entrypoint: 'consultation',
          roles: input.run.state.runtime?.actor?.roles,
          user_type: input.run.state.runtime?.actor?.user_type,
        },
      },
    });
    const plannedQuery = output.json?.query?.trim() || question;
    const ragResult = readRagSearchToolOutput(output.tool_results);
    const nextState: AgentGraphState = {
      ...state,
      current_node: 'retrieval_planner',
      retrieval: {
        query: plannedQuery,
        citations: ragResult?.citations ?? [],
        confidence: ragResult?.confidence ?? 0,
        backend_mode: ragResult?.backend_mode ?? 'pending',
      },
    };
    await saveCheckpoint({ run_id: run.run_id, state: nextState });
    return nextState;
  }

  private async runRagTool(
    input: {
      run: AgentRunRow;
      actor_id: string;
      trace_id: string;
    },
    state: AgentGraphState,
  ): Promise<AgentGraphState> {
    const query = state.retrieval?.query ?? readQuestion(state);
    const policyId = typeof state.input.policy_id === 'string'
      ? state.input.policy_id
      : undefined;
    const toolResult = await agentToolRunner.execute<RagSearchResult>('rag.search', {
      query,
      policy_id: policyId,
      limit: 3,
      create_fallback_task: false,
    }, {
      run_id: input.run.run_id,
      actor_id: input.actor_id,
      trace_id: input.trace_id,
      agent_type: 'retrieval_planner',
      entrypoint: 'consultation',
      roles: input.run.state.runtime?.actor?.roles,
      user_type: input.run.state.runtime?.actor?.user_type,
    });
    const ragResult = toolResult.output;
    const nextState: AgentGraphState = {
      ...state,
      current_node: 'rag_tool',
      retrieval: {
        query,
        citations: ragResult.citations,
        confidence: ragResult.confidence,
        backend_mode: ragResult.backend_mode,
      },
    };
    await agentStepRecorder.recordStep({
      run_id: input.run.run_id,
      node_name: 'rag_tool',
      agent_type: 'tool',
      status: 'completed',
      input: {
        query,
        policy_id: policyId ?? null,
      },
      output: {
        citation_count: ragResult.citations.length,
        confidence: ragResult.confidence,
        backend_mode: ragResult.backend_mode,
      },
      tool_calls: [{
        tool_call_id: toolResult.tool_call.tool_call_id,
        tool_name: toolResult.tool_call.tool_name,
        status: toolResult.tool_call.status,
      }],
    });
    await saveCheckpoint({ run_id: input.run.run_id, state: nextState });
    return nextState;
  }

  private async runPolicyAnalysis(
    run: AgentRunRow,
    state: AgentGraphState,
    question: string,
  ): Promise<AgentGraphState> {
    const output = await this.callJsonAgent<PolicyAnalysisOutput>({
      run: { ...run, state },
      node_name: 'policy_analysis',
      agent_type: 'policy_analysis',
      schema: 'policy_analysis',
      input: {
        question,
        citations: state.retrieval?.citations ?? [],
      },
      system_prompt: [
        'You analyze policy citations.',
        'Do not invent policies. Return JSON with result, explanation, confidence, missing_fields, matched_conditions, answer.',
      ].join(' '),
      user_prompt: wrapUntrustedContent('policy_analysis_input', {
        question,
        citations: state.retrieval?.citations ?? [],
      }),
    });
    const nextState: AgentGraphState = {
      ...state,
      current_node: 'policy_analysis',
      policy_analysis: {
        result: output.json?.result ?? 'answered_with_citation',
        matched_conditions: output.json?.matched_conditions ?? [],
        missing_fields: output.json?.missing_fields ?? [],
        explanation: output.json?.explanation ?? '',
        confidence: toConfidence(output.json?.confidence),
        answer: output.json?.answer,
      },
    };
    await saveCheckpoint({ run_id: run.run_id, state: nextState });
    return nextState;
  }

  private async runRiskJudge(
    run: AgentRunRow,
    state: AgentGraphState,
  ): Promise<AgentGraphState> {
    const output = await this.callJsonAgent<RiskJudgeOutput>({
      run: { ...run, state },
      node_name: 'risk_judge',
      agent_type: 'risk_judge',
      schema: 'risk_judge',
      input: {
        citation_count: state.retrieval?.citations.length ?? 0,
        policy_analysis: state.policy_analysis ?? null,
      },
      system_prompt: [
        'You are a risk judge.',
        'Return JSON with approved, should_fallback, reasons, confidence.',
      ].join(' '),
      user_prompt: wrapUntrustedContent('risk_judge_input', {
        retrieval: state.retrieval,
        policy_analysis: state.policy_analysis,
      }),
    });
    const nextState: AgentGraphState = {
      ...state,
      current_node: 'risk_judge',
      judge: {
        approved: output.json?.approved ?? false,
        should_fallback: output.json?.should_fallback ?? true,
        reasons: output.json?.reasons ?? [],
        confidence: toConfidence(output.json?.confidence),
      },
    };
    await saveCheckpoint({ run_id: run.run_id, state: nextState });
    return nextState;
  }

  private async callJsonAgent<TJson>(input: {
    run: AgentRunRow;
    node_name: string;
    agent_type: AgentType;
    schema: AgentOutputSchema;
    input: Record<string, unknown>;
    system_prompt: string;
    user_prompt: string;
    tools?: {
      allowed_tools: ['rag.search'];
      scope?: {
        policy_id?: string;
      };
      context: Parameters<typeof runAgentToolLoop>[0]['context'];
    };
  }): Promise<AgentJsonResponse<TJson>> {
    const model = await resolveModelForAgent(input.agent_type);
    const prompt = await findActivePromptTemplate(input.agent_type);
    const messages: LlmMessage[] = [
        {
          role: 'system',
          content: `${prompt?.content ?? input.system_prompt} Prompt version: ${prompt?.version ?? PROMPT_VERSION}.`,
        },
        { role: 'user', content: input.user_prompt },
      ];
    const requestBase = {
      model: model.model,
      response_format: 'json_object' as const,
      trace_id: input.run.trace_id ?? input.run.state.trace_id,
      run_id: input.run.run_id,
      agent_type: input.agent_type,
      prompt_version: prompt?.version ?? PROMPT_VERSION,
    };
    const loopResult = input.tools
      ? await runAgentToolLoop<TJson>({
        base_messages: messages,
        allowed_tools: input.tools.allowed_tools,
        context: input.tools.context,
        prepare_tool_input: ({ tool_name, tool_input }) => {
          if (tool_name !== 'rag.search') {
            return tool_input;
          }
          return {
            query: typeof tool_input.query === 'string' ? tool_input.query : '',
            policy_id: input.tools?.scope?.policy_id,
            limit: 3,
            create_fallback_task: false,
          };
        },
        chatCompletion: ({ messages: nextMessages, tools, tool_choice }) => (
          getLlmClient().chatCompletion<TJson>({
            ...requestBase,
            messages: nextMessages,
            tools,
            tool_choice,
          })
        ),
      })
      : null;
    const response = loopResult?.response ?? await getLlmClient().chatCompletion<TJson>({
      ...requestBase,
      messages,
    });
    const json = validateAgentOutput({
      schema: input.schema,
      json: response.json,
      agent_type: input.agent_type,
      model: model.model,
      trace_id: input.run.trace_id ?? input.run.state.trace_id,
    }) as TJson;
    await agentStepRecorder.recordStep({
      run_id: input.run.run_id,
      node_name: input.node_name,
      agent_type: input.agent_type,
      model_name: model.model,
      prompt_template_id: prompt?.template_id ?? null,
      status: 'completed',
      input: {
        ...input.input,
        prompt_version: prompt?.version ?? PROMPT_VERSION,
        provider: model.provider,
        endpoint: model.endpoint,
        model_version: model.model_version ?? null,
        deployment_location: model.deployment_location ?? null,
      },
      output: json && typeof json === 'object'
        ? json as Record<string, unknown>
        : { content: response.content },
      token_usage: usageToRecord(response.usage),
      tool_calls: loopResult?.tool_calls,
    });
    return {
      ...response,
      json,
      tool_results: loopResult?.tool_results ?? [],
    };
  }

  private async interruptForFallback(
    input: {
      run: AgentRunRow;
      actor_id: string;
      trace_id: string;
    },
    state: AgentGraphState,
    reason: string,
  ): Promise<AgentRunRow> {
    const question = readQuestion(state);
    const fallback = await fallbackService.createIfNotExists({
      actor_id: input.actor_id,
      trace_id: input.trace_id,
      source_type: 'agent_run',
      source_id: input.run.run_id,
      run_id: input.run.run_id,
      reason,
      context: {
        run_id: input.run.run_id,
        normalized_question: normalizeQuestion(question),
        policy_id: typeof state.input.policy_id === 'string' ? state.input.policy_id : null,
        citation_count: state.retrieval?.citations.length ?? 0,
        judge: state.judge ?? null,
      },
    });
    await attachFallbackTaskToRun({
      task_id: fallback.task.task_id,
      run_id: input.run.run_id,
    });

    const nextState: AgentGraphState = {
      ...state,
      current_node: 'human_fallback',
      fallback: {
        task_id: fallback.task.task_id,
        reason,
      },
      final: {
        status: 'manual_review',
        answer: 'No usable policy citation was found. Manual fallback is required.',
        citations: state.retrieval?.citations ?? [],
        next_actions: ['manual_fallback'],
      },
    };
    await agentStepRecorder.recordStep({
      run_id: input.run.run_id,
      node_name: 'human_fallback',
      agent_type: 'human_fallback',
      status: 'interrupted',
      input: {
        reason,
      },
      output: {
        fallback_task_id: fallback.task.task_id,
      },
    });
    await saveCheckpoint({
      run_id: input.run.run_id,
      state: nextState,
      status: 'interrupted',
    });

    return this.updateRun(input.run.run_id, 'interrupted', 'human_fallback', nextState);
  }

  private async updateRun(
    runId: string,
    status: 'completed' | 'interrupted',
    currentNode: string,
    state: AgentGraphState,
  ): Promise<AgentRunRow> {
    const updated = await updateRunStateIfLeased({
      run_id: runId,
      status,
      current_node: currentNode,
      state,
    });
    if (!updated) {
      throw new ApiError('CONFLICT', 'agent run worker lease lost before state update');
    }
    return updated;
  }
}

function readQuestion(state: AgentGraphState): string {
  const question = state.input.question;
  if (typeof question !== 'string' || question.trim() === '') {
    throw new ApiError('VALIDATION_ERROR', 'question is required');
  }
  return question.trim();
}

function toConfidence(value: unknown): number {
  if (typeof value !== 'number' || !Number.isFinite(value)) {
    return 0;
  }
  return Math.max(0, Math.min(1, value));
}

function usageToRecord(usage: LlmTokenUsage | null): Record<string, unknown> {
  return usage
    ? {
        prompt_tokens: usage.prompt_tokens,
        completion_tokens: usage.completion_tokens,
        total_tokens: usage.total_tokens,
      }
    : {};
}

function readRagSearchToolOutput(
  toolResults: AgentJsonResponse<unknown>['tool_results'],
): RagSearchResult | null {
  const result = toolResults?.find((item) => item.tool_name === 'rag.search')?.output;
  if (!result || typeof result !== 'object') {
    return null;
  }
  const value = result as Partial<RagSearchResult>;
  if (!Array.isArray(value.citations)) {
    return null;
  }
  return {
    status: isRagStatus(value.status) ? value.status : 'matched',
    citations: value.citations,
    confidence: typeof value.confidence === 'number' ? value.confidence : 0,
    backend_mode: isRagBackendMode(value.backend_mode)
      ? value.backend_mode
      : 'local_fallback',
    fallback_task: value.fallback_task ?? null,
    degrade_reason: value.degrade_reason,
  };
}

function isRagStatus(value: unknown): value is RagSearchResult['status'] {
  return value === 'matched' || value === 'low_confidence' || value === 'no_match';
}

function isRagBackendMode(value: unknown): value is RagSearchResult['backend_mode'] {
  return value === 'haystack_pgvector' ||
    value === 'haystack_inmemory' ||
    value === 'local_fallback';
}

function buildFinalAnswer(input: {
  analysis: string;
  citations: unknown[];
}): string {
  const firstCitation = input.citations[0] as Partial<RagCitation> | undefined;
  const citationLabel = firstCitation
    ? `${firstCitation.title ?? 'policy'} ${firstCitation.version ?? ''}`.trim()
    : 'citation';
  return `${input.analysis}\n\nCitation: ${citationLabel}`;
}

export const consultationGraphRunner = new ConsultationGraphRunner();
